name: Android

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-ffmpeg:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: ["armeabi-v7a", "arm64-v8a", "x86_64", "x86"]
        include:
          - os: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build tools
        run: |
          sudo apt install -y build-essential ninja-build

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          sdkmanager "ndk;26.1.10909125"

      - name: Build
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125
        run: |
          chmod +x build-android.sh
          ./build-android.sh --target-arch=${{ matrix.arch }}

      - name: Prepare Artifact
        run: |
          build_arch_dir=build/android/${{ matrix.arch }}
          mkdir -p ${build_arch_dir}/artifact
          mv -v ${build_arch_dir}/openssl ${build_arch_dir}/artifact/openssl
          mv -v ${build_arch_dir}/ffmpeg ${build_arch_dir}/artifact/ffmpeg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: android-ffmpeg-openssl-${{ matrix.arch }}
          path: build/android/${{ matrix.arch }}/artifact
