name: CI

on:
  push:
    tags:
      - '*'

jobs:
  windows:
    name: Windows
    uses: ./.github/workflows/windows.yml
    secrets: inherit
    
  android:
    name: Android
    uses: ./.github/workflows/android.yml
    secrets: inherit

  linux:
    name: Linux
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  release:
    name: Release 
    needs: [windows, linux, android]
    uses: ./.github/workflows/release.yml
