name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release-job:
    name: Release
    permissions:
      contents: write

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Artifact Names
        id: artifact-names
        run: |
          echo "artifact_names=$(ls -1 artifacts | awk '{ printf "%sartifacts/%s", sep, $0; sep="," }')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.artifact-names.outputs.artifact_names }}"
