name: Windows

on:
  workflow_call:
  workflow_dispatch:

jobs:
  # NOTE: It would be faster to cross compile it than using MSYS2
  build-ffmpeg:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            nasm
            curl
            git

      - name: Build
        shell: msys2 {0}
        run: |
          chmod +x build-windows.sh
          ./build-windows.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: windows-ffmpeg
          path: build/windows/ffmpeg
